// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.0.0.0
//      SpecFlow Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace IMDB.Tests
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("UpdateActorFeature")]
    public partial class UpdateActorFeatureFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "UpdateActorFeature.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "UpdateActorFeature", "\tIn order to update the actor by Id\n\tAs an API consumer\n\tI want to be able to upd" +
                    "ate actor\'s information through the API", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Updating an Actor with valid data")]
        public virtual void UpdatingAnActorWithValidData()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Updating an Actor with valid data", null, ((string[])(null)));
#line 6
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 7
 testRunner.Given("that an Actor exists in the system", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Bio",
                        "Dob",
                        "Gender"});
            table1.AddRow(new string[] {
                        "TestName",
                        "TestBio",
                        "2000-1-1",
                        "TestGender"});
#line 8
 testRunner.When("I request to update the Actor by Id with details", ((string)(null)), table1, "When ");
#line 11
 testRunner.Then("the Actor should be updated", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 12
 testRunner.And("the response status code is \'200 OK\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Updating a non-existing Actor")]
        public virtual void UpdatingANon_ExistingActor()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Updating a non-existing Actor", null, ((string[])(null)));
#line 14
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 15
 testRunner.Given("that an actor does not exist in the system", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 16
 testRunner.When("I request to update the Actor by Id with details Name: \'TestName\' Bio: \'TestBio\' " +
                    "Dob: \'2000-1-1\' and Gender: \'TestGender\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 17
 testRunner.Then("the response status code is \'404 Not Found\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Updating an Actor with invalid data")]
        [NUnit.Framework.TestCaseAttribute("", "TestBio", "2000-1-1", "TestGender", null)]
        [NUnit.Framework.TestCaseAttribute("TestName", "", "2000-1-1", "TestGender", null)]
        [NUnit.Framework.TestCaseAttribute("TestName", "TestBio", "", "TestGender", null)]
        [NUnit.Framework.TestCaseAttribute("TestName", "TestBio", "2000-1-1", "", null)]
        [NUnit.Framework.TestCaseAttribute("", "", "2000-1-1", "TestGender", null)]
        [NUnit.Framework.TestCaseAttribute("", "TestBio", "", "TestGender", null)]
        [NUnit.Framework.TestCaseAttribute("", "TestBio", "2000-1-1", "", null)]
        [NUnit.Framework.TestCaseAttribute("TestName", "", "", "TestGender", null)]
        [NUnit.Framework.TestCaseAttribute("TestName", "", "2000-1-1", "", null)]
        [NUnit.Framework.TestCaseAttribute("TestName", "TestBio", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("", "", "", "TestGender", null)]
        [NUnit.Framework.TestCaseAttribute("", "", "2000-1-1", "", null)]
        [NUnit.Framework.TestCaseAttribute("TestName", "", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("", "TestBio", "", "", null)]
        [NUnit.Framework.TestCaseAttribute("", "", "2000-1-1", "", null)]
        [NUnit.Framework.TestCaseAttribute("", "", "", "", null)]
        public virtual void UpdatingAnActorWithInvalidData(string name, string bio, string dob, string gender, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Updating an Actor with invalid data", null, exampleTags);
#line 19
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 20
 testRunner.Given("that an Actor exists in the system", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 21
 testRunner.When(string.Format("I request to update the Actor by Id with details Name: \'{0}\' Bio: \'{1}\' Dob: \'{2}" +
                        "\' and Gender: \'{3}\'", name, bio, dob, gender), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 22
 testRunner.Then("the response status code is \'400 Bad Request\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
